name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']
    steps:
      - uses: actions/checkout@v7
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: none
      - uses: ramsey/composer-install@v3
      - run: composer test
      - run: composer tools:upgrade
      - run: composer tools:run:php-lint
      - run: composer tools:run:phpstan
      - run: composer tools:run:php-cs-fixer
